<?php
	$username = FreshRSS_Context::$user_conf->instapaper_username;
	$password = FreshRSS_Context::$user_conf->instapaper_password;
	$keyboard_shortcut = FreshRSS_Context::$user_conf->instapaper_keyboard_shortcut;
?>

<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="keyboard_shortcut"><?php echo _t('ext.instapaperButton.configure.keyboard_shortcut'); ?></label>
		<div class="group-controls">
			<input type="text" name="keyboard_shortcut" id="keyboard_shortcut" class="ib_keyboard_shortcut" maxlength="1" value="<?php echo $keyboard_shortcut; ?>">
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
		</div>
	</div>
</form>

<?php if ($this->isEnabled() && empty($username) && empty($password)): ?>
<form action="<?php echo _url('instapaperButton', 'saveCredentials'); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="username"><?php echo _t('ext.instapaperButton.configure.username'); ?></label>
		<div class="group-controls">
			<input type="text" name="username" id="username" class="ib_username" value="<?php echo htmlspecialchars($username); ?>">
		</div>
	</div>

	<div class="form-group">
		<label class="group-name" for="password"><?php echo _t('ext.instapaperButton.configure.password'); ?></label>
		<div class="group-controls">
			<input type="password" name="password" id="password" class="ib_password" value="">
		</div>
	</div>

	<div class="alert alert-warn">
		<?php echo _t('ext.instapaperButton.configure.credentials_description'); ?>
	</div>
	
	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('ext.instapaperButton.configure.connect_to_instapaper'); ?></button>
		</div>
	</div>
</form>
<?php elseif (!$this->isEnabled()): ?>
	<p class="alert alert-error">
		<?php echo _t('ext.instapaperButton.configure.extension_disabled'); ?>
	</p>
<?php endif ?>

<?php if (!empty($username) || !empty($password)): ?>
	<p class="alert alert-success">
		<?php echo _t('ext.instapaperButton.configure.connected_to_instapaper', $username); ?>
	</p>
	<form action="<?php echo _url('instapaperButton', 'revokeAccess'); ?>" method="post">
		<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('ext.instapaperButton.configure.revoke_access'); ?></button>
			</div>
		</div>
	</form>
<?php endif ?>